"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_d%r+j2!)h3t6ex)@h4und72y$ix5_q^(5nwva=5&4+1wq(n(7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis', # Tambahkan aplikasi GIS
    'core',             # Tambahkan aplikasi Anda
    'rest_framework',  # Tambahkan Django REST Framework
    'rest_framework.authtoken',  # Token Authentication
    'dj_rest_auth',    # Tambahkan dj-rest-auth
    'django.contrib.sites',  # Tambahkan sites framework
    'allauth',         # Tambahkan django-allauth
    'allauth.account', # Akun allauth
    'allauth.socialaccount', 
    'dj_rest_auth.registration', # Registrasi dengan dj-rest-auth
    'corsheaders',
    
]

SITE_ID = 1  # Pastikan SITE_ID sesuai dengan situs Anda

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # <-- INI BAGIANNYA
        'NAME': 'gis_platform_db',
        'USER': 'postgres',
        'PASSWORD': '123456789',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- PENGATURAN GIS LENGKAP ---
OSGEO4W_DIR = r'C:\Users\Synner\AppData\Local\Programs\OSGeo4W' # Ganti jika path berbeda
if os.path.isdir(OSGEO4W_DIR):
    GDAL_LIBRARY_PATH = os.path.join(OSGEO4W_DIR, 'bin', 'gdal311.dll') # Ganti gdal311.dll jika perlu
    GEOS_LIBRARY_PATH = os.path.join(OSGEO4W_DIR, 'bin', 'geos_c.dll')
    PROJ_LIBRARY_PATH = os.path.join(OSGEO4W_DIR, 'bin', 'proj.dll')
    os.environ['PROJ_LIB'] = os.path.join(OSGEO4W_DIR, 'share', 'proj')


# --- KONFIGURASI DJANGO REST FRAMEWORK & OTENTIKASI ---
REST_FRAMEWORK = {
    # Aturan default: SEMUA endpoint API mewajibkan user untuk login.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Otentikasi default sekarang menggunakan Token, bukan lagi Session
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Menambahkan ini agar email konfirmasi ditampilkan di console saat development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Alamat default untuk React dev server Vite
    "http://127.0.0.1:5173",
]