# Generated by Django 5.2.6 on 2025-10-01 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcollaborator',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectlayer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mapproduct',
            name='map_file',
        ),
        migrations.RemoveField(
            model_name='mapproduct',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='mapproduct',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='mapproduct',
            name='map_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapproduct',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publisher'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborating_projects', through='core.ProjectCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='map_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mapproduct'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='projectlayer',
            name='added_at',
        ),
    ]
